export const catalogEn = {
  "没有符合条件的矿机": "No miners match your filters",
  "试试调整价格、日产出范围或搜索关键词。": "Try changing the price, daily output range or search terms.",
  "矿机信息列表": "Miner listings",
  "矿机 / 来源": "Miner / Source",
  "全机日产出": "Daily output",
  "BEM / 天": "BEM / day",
  "当前挂牌价": "Asking price",
  "购入整机价": "Purchase price",
  "目标整机价": "Target price",
  "目标募集金额": "Funding target",
  "目标募集金额、每份认购金额及挖矿中的购入金额均含商城 1% 买方手续费。价格筛选和日产能价：募集中按商城标价、挖矿中按含费购入金额、整机出售中按当前挂牌价计算。": "Funding targets, subscription prices and mining-stage purchase costs include the marketplace’s 1% buyer fee. Price filters and price per daily BEM use the marketplace list price during fundraising, the fee-inclusive purchase cost during mining, and the current asking price during sale.",
  "日产能价": "Price per daily BEM",
  "BNB / (BEM / 天)": "BNB / (BEM / day)",
  "募集进度": "Funding progress",
  "出售状态": "Sale status",
  "挖矿状态": "Mining status",
  "操作": "Actions",
  "{count} 位参与者": "{count} participants",
  "演示来源": "Demo sources",
  "预计日产出": "Estimated daily output",
  "当前估计日产出": "Current estimated output",
  "每份 {amount} BNB": "{amount} BNB per share",
  "整机挂牌价格": "Whole-miner asking price",
  "历史购入金额": "Original purchase price",
  "历史购入金额 · 含买方费用": "Purchase cost · Buyer fee included",
  "整机价 ÷ 日产出": "Price ÷ daily output",
  "日产出暂不可用": "Daily output unavailable",
  " / 100 份": " / 100 shares",
  "募集完成 · 待购机": "Funded · Awaiting purchase",
  "剩余 {count} 份": "{count} shares remaining",
  "已运行 {count} 天": "Running for {count} days",
  "查看矿机": "View miner",
  "左右滑动查看完整矿机信息": "Swipe sideways to see all miner details",
  "参与拼矿": "Mine together",
  "从矿机产出出发，找到适合你的参与方式。": "Compare miner output and find your way to join.",
  "演示数据": "Demo data",
  "项目状态": "Project status",
  "项目总览": "Project overview",
  "搜索矿机编号、TapeOut / Behemoth": "Search miner ID, TapeOut / Behemoth",
  "搜索矿机": "Search miners",
  "清除搜索": "Clear search",
  "筛选": "Filters",
  "矿机排序": "Sort miners",
  "市场来源": "Marketplace",
  "全部来源": "All marketplaces",
  "矿机系列": "Miner series",
  "全部系列": "All series",
  "全机日产出 · BEM / 天": "Daily output · BEM / day",
  "最低": "Min",
  "最高": "Max",
  "最低日产出": "Minimum daily output",
  "最高日产出": "Maximum daily output",
  "整机价格 · BNB": "Whole-miner price · BNB",
  "最低价格": "Minimum price",
  "最高价格": "Maximum price",
  "最低值不能大于最高值，请调整筛选范围。": "Minimum cannot exceed maximum. Please adjust the range.",
  "同一矿机可能同时出现在两个市场，列表仅展示一次。": "A miner listed on both marketplaces appears only once.",
  "重置筛选": "Reset filters",
  "项目概况": "Projects at a glance",
  "个项目": " projects",
  " · 已筛选": " · Filtered",
  "日产出为估计值，随矿机运行情况变化": "Daily output is an estimate and varies with miner performance.",
  "目标总日产出": "Target daily output",
  "当前总日产出": "Current daily output",
  "已募集份额": "Funded shares",
  "合计挂牌金额": "Total asking price",
  "合计购入金额": "Total purchase price",
  "{funded} / {total} 份": "{funded} / {total} shares",
  "查看全部": "View all",
  "当前展示演示项目与演示来源标签，尚未接入 TapeOut 官方及 Firsto 实时市场。": "Projects and marketplace labels are for demonstration. Live TapeOut and Firsto market data is not connected yet.",
  "日产能价 = 对应整机价格 ÷ 全机估计日产出，单位为 BNB / (BEM / 天)，不代表回本时间。": "Price per daily BEM = whole-miner price ÷ estimated daily output, in BNB / (BEM / day). This is not a payback period.",
  "TapeOut 官方": "TapeOut Official",
  "募集中": "Fundraising",
  "待购机": "Awaiting purchase",
  "挖矿中": "Mining",
  "整机出售中": "For sale",
  "编号从低到高": "ID: low to high",
  "整机价格从低到高": "Price: low to high",
  "整机价格从高到低": "Price: high to low",
  "目前募集份额最多": "Most shares funded",
  "全机日产出从高到低": "Daily output: high to low",
  "日产能价从低到高": "Price per daily BEM: low to high"
};
