export const homeEn={
 "拼矿 BEMine · 一起参与 TapeOut":"BEMine · Together in TapeOut", "拼矿已创建项目":"Projects on BEMine",

 '当前币价':'Current BEM price','正在获取行情':'Loading price','行情暂不可用':'Price unavailable','来源：':'Source: ',
 '每 15 秒更新 · {time}':'15-second refresh · {time}', 'BEM/WBNB × BNB/USDT · 参考价':'BEM/WBNB × BNB/USDT · Indicative',
 '切换为日常模式':'Switch to light mode','切换为深色模式':'Switch to dark mode','深色':'Dark','日常':'Light',
 '贝矿 BEMine · 一起参与 TapeOut':'BEMine · Together in TapeOut',
 '一份投入，十分热爱，':'One share. Shared passion.',
 '百分参与，万份回报。':'Fully involved. More to discover.',
 '从一份矿机开始，与更多 Tapeouters 共同持有、共享产出，参与 TapeOut 的每一步成长。':'Start with one share. Own miners together, share their output, and grow with the TapeOut community.',
 '寻找我的第一份矿机':'Find my first miner share',
 '了解如何参与':'How it works',
 '「万份回报」为品牌愿景，不代表收益承诺。实际产出会随矿机及协议状态变化。':'Our slogan expresses an aspiration, not a promise of returns. Actual output varies with miner performance and protocol conditions.',
 '播放背景动效':'Play miner animation','暂停背景动效':'Pause miner animation','播放动效':'Play motion','暂停动效':'Pause motion',
 '墨绿色芯片与 BEM 金币':'An emerald microchip and gold BEM coins',
 '初衷愿景':'Our purpose',
 '让每一位 Tapeouter，都能享受挖矿的乐趣。':'The joy of mining, for every Tapeouter.',
 '我们相信，参与 TapeOut 不应只属于少数人。无论投入多少，每一份热爱都值得有一个参与的入口。':'We believe participation in TapeOut should be open to more people. Every contribution, however small, deserves a way in.',
 'BEMine 希望通过共同持有矿机，降低独自购机的资金门槛，让每一位 Tapeouter 在参与生态建设的同时，也有能力享受挖矿的乐趣。':'Through shared miner ownership, BEMine aims to lower the upfront cost of participation, so every Tapeouter can help build the ecosystem and experience the joy of mining.',
 '从一份开始，一起建设，一起成长。':'Start with one share. Build together. Grow together.',
 '每一份参与，都在这里汇聚。':'Every contribution counts.',
 '平台统计 · 演示数据':'Platform statistics · Demo',
 '累计立项':'Projects created','个':'projects','贝矿已创建项目':'Projects on BEMine',
 '参与 Tapeouters':'Participating Tapeouters','位':'wallets','按参与地址去重':'Unique participating wallets',
 '管理矿机':'Managed miners','台':'miners','已完成购机并管理':'Purchased and managed',
 '当前预估日产':'Est. daily output','全机产出 · 分配前':'Gross miner output',
 '平台统计用于页面演示，不代表实际运营规模；币价为独立行情。参与人数按钱包地址统计，筹款中的目标矿机不计入已管理矿机与当前日产。':'Platform totals are illustrative; the token price is sourced independently. Participants are counted by wallet address. Fundraising targets are excluded from managed miners and current output.',
 '找到属于你的参与方式。':'Find your way to participate.',
 '查看项目总览':'Explore all projects',
 '一起出资，开启下一台矿机。':'Pool contributions for the next miner.',
 '共同持有，按份额分享产出。':'Own together and share the output.',
 '共同决定，让矿机有序流转。':'Decide together when to sell a miner.',
 '剩余 {count} 份可参与':'{count} shares available',
 '全机预估日产 {amount} BEM':'Est. output: {amount} BEM/day',
 '一起拼矿，':'Own miners together.', '也一起决定。':'Decide together.',
 '资产有归属，产出有记录，':'Clear ownership. Recorded output.',
 '重大事项由共同持有人参与决定。':'Co-owners take part in deciding major matters.',
 '了解平台规则':'Read the rules',
 '从 1 份开始':'Start with 1 share',
 '每台矿机共有100份额，每个地址可选择持有数量，至多49份。':'Each miner has 100 shares. Each wallet chooses how many to hold, up to 49 shares.',
 '按份分享真实产出':'Share actual mining output',
 '共同参与重要决策':'Have a say in key decisions',
 '整机出售需要参与地址数和持有份额双过半。':'A whole-miner sale requires a majority of both eligible wallets and shares.',
 '把记录摆在明处':'Keep records in plain sight',
 '共持BEM矿机，共享BEM人生':'Own BEM miners together. Share the BEM life.',
 'Tapeouters 围绕共同持有的矿机，一起建设生态':'Tapeouters building the ecosystem around a shared miner',
 '让参与更轻一点，让每一份选择更清楚一点。':'Easier participation. Better-informed choices.',
 '查看我的资产':'View my portfolio','查看公开记录':'View public records',
 '募集中':'Fundraising','挖矿中':'Mining','整机出售中':'For sale',
};
