// English copy for the asset workspace, details and demo dialogs.
export const platformEn = {
 "拼矿总览":"BEMine overview",

  "矿机详情": "Miner details",
  "矿机资产": "Miner asset",
  "状态": "Status",
  "我的份额": "My shares",
  "投入金额": "Amount contributed",
  "预估日产出 ": "Est. daily output ",
  "/ 我的": "/ my share",
  "每份认购金额": "Price per share",
  "全机预估日产出": "Est. whole-miner daily output",
  "募集进度": "Funding progress",
  "已募集": "Funded",
  " / 100 份": " / 100 shares",
  " 位参与者": " participants",
  "剩余 2 天 14 小时": "2 days 14 hours left",
  "查看项目 · 参与拼矿": "View project · Join pool",
  "查看矿机": "View miner",
  "时间 · 北京时间": "Time · UTC+8",
  "类型": "Type",
  "相关矿机": "Miner",
  "金额": "Amount",
  "记录": "Record",
  "资产工作台": "ASSET WORKSPACE",
  "更多服务": "MORE SERVICES",
  "矿机质押": "Miner collateral",
  "即将开放": "Coming soon",
  "最优质保": "Quality assurance",
  "筹备中": "In preparation",
  "平台规则": "Platform rules",
  "页面预览 · 演示数据": "Preview · Demo data",
  "共同持有，透明参与。": "Shared ownership. Transparent participation.",
  "打开导航": "Open navigation",
  "工作台": "Workspace",
  "演示预览": "Demo preview",
  "参与指南": "Participation guide",
  "连接钱包": "Connect wallet",
  "你的矿机资产，从这里看清。": "Your miner assets, at a glance.",
  "连接钱包后，查看个人持仓、矿机收益与待办事项。": "Connect your wallet to view holdings, mining rewards and next steps.",
  "当前为演示环境，使用演示账户体验，不请求真实钱包签名。": "This is a demo. Explore with a demo account; no real wallet signature is requested.",
  "资产总览": "My portfolio",
  "掌握你的矿机持仓、收益与待办事项。": "Track your miner holdings, rewards and next steps.",
  "2026 年 09 月 25 日": "September 25, 2026",
  "参与拼矿": "Join a mining pool",
  "累计投入": "Total contributed",
  "分布于 ": "Across ",
  " 台矿机 · 不代表当前估值": " miners · Not a current valuation",
  "累计到账收益": "Total rewards received",
  " 最近一日产出": " Latest daily output",
  "当前可领取": "Available to claim",
  "本次演示收益已领取": "Demo rewards claimed",
  "查看收益批次": "View reward batches",
  "持有矿机": "Miners held",
  "台": "miners",
  "共持有 ": "Holding ",
  " 个整数份额": " whole shares in total",
  "矿机收益": "Mining rewards",
  "我的每日到账 · BEM": "My daily receipts · BEM",
  "近 7 天": "Last 7 days",
  "近 30 天": "Last 30 days",
  "实际到账收益 · 演示": "Rewards received · Demo",
  "收益随矿机状态与协议产出变化，历史记录不代表未来收益。": "Rewards vary with miner status and protocol output. Past results do not indicate future returns.",
  "待办事项": "Next steps",
  "前往领取 ": "Claim rewards ",
  "参与矿机出售决策": "Vote on a miner sale",
  "Behemoth #8204 · 剩余 17 小时": "Behemoth #8204 · 17 hours left",
  "查看提案 ": "View proposal ",
  "每笔分配都有记录": "Every distribution has a record",
  "我的矿机": "My miners",
  "收益和投票权随你的有效份额计算": "Rewards and voting power follow your eligible shares",
  "查看全部资产": "View all holdings",
  "正在募集": "Open for funding",
  "从一份开始，参与矿机共持": "Start with one share. Own a miner together.",
  "探索全部项目": "Explore all projects",
  "← 返回项目大厅": "← Back to projects",
  "矿机身份": "Miner identity",
  "购机募集金额": "Purchase funding target",
  "共同参与者": "Participants",
  "位": "wallets",
  "出资份额": "Ownership shares",
  "已完成全部募集": "Fully funded",
  "募集截止：09 月 28 日 22:00": "Funding closes: September 28, 22:00 (UTC+8)",
  "募集资金": "Raise funds",
  "完成购机": "Purchase miner",
  "收益分配": "Reward distribution",
  "资产详情": "Asset details",
  "收益记录": "Reward records",
  "共同决策": "Shared decisions",
  "参与者": "Participants",
  "矿机信息": "Miner information",
  "矿机系列": "Miner series",
  "矿机编号": "Miner ID",
  "认购资产": "Contribution asset",
  "份额结构": "Share structure",
  "100 份，每份 1%": "100 shares, 1% each",
  "单地址可持有": "One wallet may hold",
  "最多 100 份（含挂牌锁定份额）": "Up to all 100 shares, including listed shares",
  "收益领取": "Reward claim",
  "已入账 BEM 可随时领取": "Booked BEM can be claimed at any time",
  "收益有效期": "Reward validity",
  "已入账收益永久保留": "Booked rewards never expire",
  "数据状态": "Data status",
  "演示数据 · 尚未接入链上": "Demo data · Not connected on-chain",
  "每笔挖矿收益如何分配": "How mining rewards are distributed",
  "出资人 ": "Contributors ",
  "平台费用 ": "Platform fee ",
  "收益分配记录": "Reward distribution records",
  "记录仅用于页面演示": "Records are for demonstration only",
  "共同决定矿机的下一步": "Decide the miner’s next step together",
  "出售需要全体快照参与地址与份额双过半。": "A sale requires over half of both snapshot wallets and snapshot shares to approve.",
  "买入满 7 天后可发起出售提案。投票和执行窗口为 24 小时。": "Sale proposals can be submitted 7 days after purchase. Voting and execution share a 24-hour window.",
  "进入共同决策": "Open shared decisions",
  "人数按钱包地址统计": "Participants are counted by wallet address",
  " 份": " shares",
  "以上为部分演示持仓。": "A selection of demo holdings is shown above.",
  "参与这个项目": "Join this project",
  "我的项目权益": "My project ownership",
  "从一份开始": "Start with one share",
  "共同持有，按份分配": "Own together. Share the output.",
  "BNB / 份": "BNB / share",
  "每份拥有该矿机 1% 的分配权益": "Each share carries 1% of this miner’s distribution rights",
  "选择认购份数": "Choose your shares",
  "最多 ": "Up to ",
  "减少一份": "Remove one share",
  "认购份数": "Shares to subscribe",
  "增加一份": "Add one share",
  "最大": "Max",
  "本次投入": "Your contribution",
  "认购后新增 ": "Add ",
  " 的项目份额": " in project shares",
  "请输入 1–": "Enter a whole number from 1 to ",
  " 之间的整数。": ".",
  "确认认购": "Confirm subscription",
  "演示操作，不连接钱包或发起链上交易。": "Demo only. No wallet connection or on-chain transaction.",
  "我的持仓": "My holdings",
  "查看收益": "View rewards",
  "查看整机出售": "View whole-miner sale",
  "购机前结清原矿主收益": "The previous owner’s rewards are settled before purchase",
  "按有效份额分配后续产出": "Future output follows eligible ownership shares",
  "交易市场": "Marketplace",
  "灵活调整持仓，让每一笔转让清晰可见。": "Adjust your holdings with clear, traceable transfers.",
  "出售我的份额": "Sell my shares",
  "份额交易": "Share trading",
  "整机出售": "Whole-miner sales",
  "挂牌中的份额仍保留收益权。成交时先结清卖方收益，成交款扣除 1% 费用后待领取。": "Listed shares retain reward rights. The seller’s rewards are settled before a trade; sale proceeds are available to claim after a 1% fee.",
  "矿机": "Miner",
  "出售份额": "Shares for sale",
  "每份价格": "Price per share",
  "全部买入": "Buy all",
  "卖方": "Seller",
  "买入": "Buy",
  "我的挂单": "My listings",
  "TapeOut #16210 · 5 份 · 0.068 BNB / 份": "TapeOut #16210 · 5 shares · 0.068 BNB / share",
  "演示挂单已撤销，5 份已解锁": "Demo listing cancelled. 5 shares unlocked.",
  "撤销挂单": "Cancel listing",
  "暂无进行中的挂单": "No active listings",
  "你可以出售部分份额，或继续持有并领取收益。": "Sell some shares, or keep holding and claiming rewards.",
  "双过半决策已通过 · 挂牌剩余 5 天 12 小时": "Double majority approved · 5 days 12 hours left",
  "成员分配 ": "Member distribution ",
  "约 99%": "Approx. 99%",
  "整机售价": "Whole-miner price",
  "购买整台矿机": "Buy whole miner",
  "整机进入出售状态后，份额成交暂停；已有份额挂单仍可撤销。": "Share trading pauses while the whole miner is listed for sale. Existing share listings can still be cancelled.",
  "收益中心": "Rewards center",
  "把每一笔归集、分配与领取看清楚。": "See each collection, allocation and claim clearly.",
  "演示记录已刷新": "Demo records refreshed",
  "刷新记录": "Refresh records",
  "当前可领取收益": "Claimable rewards",
  "本次演示领取已完成": "Demo claim completed",
  "来自 3 台矿机 · 已入账可随时领取": "From 3 miners · Booked rewards are ready to claim",
  "已领取": "Claimed",
  "领取收益": "Claim rewards",
  "待领取 BNB": "BNB to claim",
  "查看款项": "View proceeds",
  "已入账 BEM 权益永久保留；本人可随时领取。": "Booked BEM entitlements never expire; you can claim them at any time.",
  "演示记录；已入账收益永久保留": "Demo records; booked rewards never expire",
  "记账日期": "Accounting date",
  "我的收益": "My rewards",
  "永久有效": "Never expires",
  "可领取": "Claimable",
  "随时领取": "Claim at any time",
  "任何人可归集矿机收益；本人可随时领取已入账的 BEM 和 BNB，无领取间隔。": "Anyone may collect mining rewards. Each owner can claim booked BEM and BNB at any time, without a claim cooldown.",
  "权益归属": "Reward ownership",
  "份额转让前的已归属收益仍归原持有人；转让不会带走已入账收益。": "Rewards accrued before a share transfer remain with the original holder; booked rewards do not transfer with shares.",
  "重要决定，由共同持有这台矿机的人一起做。": "Important decisions belong to the people who own this miner together.",
  "发起出售提案": "Propose a sale",
  "已投票": "Voted",
  "待我投票": "Awaiting my vote",
  "投票及执行剩余 17 小时": "17 hours left to vote and execute",
  "提案 #003 · Behemoth #8204": "Proposal #003 · Behemoth #8204",
  "以 8.6000 BNB 出售整台矿机": "Sell the whole miner for 8.6000 BNB",
  "通过后将在本站挂牌。成交前结清原成员收益，出售款按有效份额分配。": "Once approved, the miner can be listed here. Existing members’ rewards are settled before sale, and proceeds follow eligible shares.",
  "拟出售价格": "Proposed sale price",
  "参考市场价格": "Market reference price",
  "价格偏差": "Price difference",
  "参与地址多数": "Wallet majority",
  "须超过 9 个快照参与地址赞成": "More than 9 snapshot wallets must approve",
  "持有份额多数": "Share majority",
  "须超过 50 份赞成": "More than 50 shares must approve",
  "我的投票权": "My voting power",
  "1 个地址 · 20 份": "1 wallet · 20 shares",
  "已投": "Voted: ",
  "赞成": "For",
  "反对": "Against",
  "票": "",
  "赞成出售": "Approve sale",
  "双过半已达成，请在截止前执行挂牌。": "Both majorities reached. Execute the listing before the deadline.",
  "执行挂牌": "Execute listing",
  "两道门槛，同一项决定": "Two majorities. One shared decision.",
  "人数和份额都严格过半，提案才具备执行条件。": "Both wallet count and shares must be strictly over half before execution.",
  "以提案前的持仓快照计算": "Based on the pre-proposal holdings snapshot",
  "每个符合资格的地址投一次票": "One vote per eligible wallet address",
  "投票后不能修改": "Votes cannot be changed",
  "达标后可立即执行挂牌": "Execute as soon as both thresholds are met",
  "必须在 24 小时窗口内执行": "Execution must occur within the 24-hour window",
  "地址数须严格过半；低于实际购机成本须至少 60 份赞成，其余须超过 50 份。": "More than half the snapshot wallets must approve. Below actual purchase cost, at least 60 shares must approve; otherwise, more than 50 shares.",
  "“人数”按钱包地址计算，不代表经过身份核验的自然人数。": "Participant counts refer to wallet addresses, not identity-verified individuals.",
  "公开记录": "Public records",
  "追溯资金流向，核对每一笔分配。": "Trace the flow of funds and verify each distribution.",
  "拼矿-演示记录.csv": "BEMine-demo-records.csv",
  "演示记录已导出": "Demo records exported",
  "导出 CSV": "Export CSV",
  "累计分配 · 演示": "Total distributed · Demo",
  "份额交易金额 · 演示": "Share trading volume · Demo",
  "整机出售平台费率": "Whole-miner sale platform fee",
  "全部记录": "All records",
  "资金记录与合约身份": "Fund records and contract identity",
  "正式项目须由指定工厂登记。当前页面为演示环境，记录编号不对应真实链上交易。": "Official projects must be registered by the designated factory. This is a demo; record IDs do not represent real on-chain transactions.",
  "查看合约信息": "View contract information",
  "公开规则 · 明确权益 · 可核对的记录": "Public rules · Clear rights · Verifiable records",
  "演示环境 · 不发生真实资金交易": "Demo environment · No real funds are transacted",
  "关闭提示": "Dismiss notification",
  "关闭弹窗": "Close dialog",
  "页面演示": "DEMO PREVIEW",
  "体验你的资产工作台": "Explore your asset workspace",
  "使用演示账户查看持仓、收益和投票流程。此预览不会请求钱包签名或连接真实账户。": "Use a demo account to explore holdings, rewards and voting. This preview will not request wallet signatures or connect a real account.",
  "已进入演示账户": "Demo account opened",
  "使用演示账户": "Use demo account",
  "已退出演示账户": "Demo account signed out",
  "退出演示账户": "Sign out of demo account",
  " · 每份占该矿机 1%": " · Each share represents 1% of this miner",
  "认购份额": "Subscription shares",
  "本次仅演示认购结果，不扣款、不发送交易。实际产出存在波动。": "This only demonstrates subscription results. No payment or transaction is sent. Actual output can vary.",
  "确认演示认购": "Confirm demo subscription",
  "领取矿机收益": "Claim mining rewards",
  "3 台矿机合计 ": "Total from 3 miners: ",
  "。正式领取时，每台矿机需要独立确认交易。": ". Live claims require a separate transaction confirmation for each miner.",
  "矿机 #": "Miner #",
  "演示领取完成：0.6842 BEM": "Demo claim completed: 0.6842 BEM",
  "演示领取全部收益": "Claim all demo rewards",
  "矿池 · 购机余款": "Pool · Purchase surplus",
  "份额市场 · 成交款": "Share market · Sale proceeds",
  "两笔款项位于不同合约，正式领取需分别确认。": "The two amounts are held by different contracts and require separate confirmations for live claims.",
  "已完成 BNB 领取流程演示": "BNB claim demo completed",
  "体验领取流程": "Try the claim flow",
  "确认": "Confirm ",
  "出售": " sale",
  "Behemoth #8204 · 拟售价格 8.6000 BNB": "Behemoth #8204 · Proposed price: 8.6000 BNB",
  "你的快照投票权": "Your snapshot voting power",
  "1 个地址 / 20 份": "1 wallet / 20 shares",
  "你的选择": "Your choice",
  "反对出售": "Reject sale",
  "投票后不能修改。若双过半达成，成员可在截止前执行挂牌。": "Votes cannot be changed. If both majorities are reached, a member may execute the listing before the deadline.",
  "演示投票已记录": "Demo vote recorded",
  "确认演示投票": "Confirm demo vote",
  "买入矿机份额": "Buy miner shares",
  " · 可购买 ": " · Available: ",
  "买入份数": "Shares to buy",
  "应付金额": "Amount due",
  "每池共 100 份，单地址可持有全部份额；此页买入仅作演示。": "Each pool has 100 shares. One wallet may hold all of them; this purchase is only a demo.",
  "已完成份额买入流程演示": "Share purchase demo completed",
  "确认演示买入": "Confirm demo purchase",
  "TapeOut #16210 · 可用 49 份": "TapeOut #16210 · 49 shares available",
  "本次挂牌": "This listing",
  "5 份": "5 shares",
  "全部成交后实收": "Net proceeds if fully sold",
  "卖方支付成交额 1% 的费用。未成交份额继续获得收益，支持撤销挂牌。": "The seller pays a 1% trading fee. Unsold shares keep earning rewards, and listings can be cancelled.",
  "演示挂单已创建": "Demo listing created",
  "创建演示挂单": "Create demo listing",
  "TapeOut #15832 · 售价 5.8000 BNB": "TapeOut #15832 · Price: 5.8000 BNB",
  "成交会先结清原持有人的矿币，再将整台矿机转给买家。此操作购买的是整机，不是共持份额。": "The previous owners’ mining rewards are settled before the whole miner transfers to the buyer. This purchases the entire miner, not pooled shares.",
  "已完成整机购买流程演示，不发生实际过户": "Whole-miner purchase demo completed. No real ownership transfer occurred.",
  "确认演示购买": "Confirm demo purchase",
  "执行矿机挂牌": "Execute miner listing",
  "双过半已达成。按批准价格 8.6000 BNB 挂牌，有效期为 7 天。": "Both majorities have been reached. List at the approved 8.6000 BNB price for 7 days.",
  "已完成挂牌执行流程演示": "Listing execution demo completed",
  "确认演示挂牌": "Confirm demo listing",
  "持有矿机满 7 天后可参与提案。每个成员每 7 天最多发起一次，投票与执行窗口为 24 小时。": "A sale can be proposed 7 days after the miner is purchased. Each member may propose once every 7 days. Voting and execution share a 24-hour window.",
  "当前演示矿机已有进行中的提案。请先查看并参与现有决策。": "This demo miner already has an active proposal. Please review and participate in that decision first.",
  "查看当前提案": "View current proposal",
  "服务正在筹备，具体适用范围与服务规则将在开放时公布。": "This service is in preparation. Eligibility and service rules will be published when it opens.",
  "知道了": "Got it",
  "未来可通过矿机质押获得流动资金，并按约定期限回赎。": "Use your miner as collateral to access liquidity and redeem it within the agreed term.",
  "该功能尚未开放，当前不接受质押、出资或借款。": "This service is not yet open. No collateral, funding or loans are currently accepted.",
  "合约与矿机身份": "Contract and miner identity",
  "正式项目以指定工厂的登记信息为准，名称相同不代表官方项目。": "Official status depends on registration by the designated factory. A matching name does not establish official status.",
  "环境": "Environment",
  "本地演示": "Demo environment",
  "正式合约地址": "Production contract address",
  "尚未配置": "Not configured",
  "链上交易": "On-chain transactions",
  "未启用": "Disabled",
  "关闭": "Close",
  "记录详情": "Record details",
  "此条记录仅用于页面演示，不对应真实链上交易。": "This record is for demonstration only and does not represent a real on-chain transaction.",
  "时间": "Time",
  "币种": "Asset",
  "演示编号": "Demo record ID",
  "参与规则": "Participation rules",
  "01 · 共同出资": "01 · Contribute together",
  "每台矿机共 100 个整数份额，单地址可认购全部份额，以 BNB 认购。": "Each miner has 100 whole shares. One wallet may subscribe for all of them in BNB.",
  "02 · 按份分配": "02 · Share the output",
  "矿机实际产出中，99% 分配给出资人，1% 用于平台运营费用。": "Of the miner’s actual output, 99% goes to contributors and 1% covers platform operations.",
  "03 · 归集后本人领取": "03 · Collect, then claim personally",
  "04 · 共同决定退出": "04 · Decide an exit together",
  "了解了": "Understood",
  "贝矿总览": "BEMine overview",
  "募集中": "Funding",
  "待购机": "Awaiting purchase",
  "挖矿中": "Mining",
  "整机出售中": "For sale",
  "已结束": "Closed",
  "可退款": "Refund available",
  "份额认购": "Share subscription",
  "项目总览": "Project overview",
  "{count}日演示收益趋势，最近一日产出0.8488 BEM": "{count}-day demo reward trend. Latest daily output: 0.8488 BEM",
  "查看{id}详情": "View miner {id} details",
  "已运行 {count} 天": "Running for {count} days",
  "还剩 {count} 份": "{count} shares remaining",
  "{count} 位共同参与者": "{count} participants",
  "{count} 份": "{count} shares",
  "演示认购成功：{count} 份": "Demo subscription confirmed: {count} shares",
  "时间,类型,矿机,金额,币种,演示记录": "Time,Type,Miner,Amount,Asset,Demo record",
  "09 月 26 日 08:00": "September 26, 08:00",
  "10 月 01 日 08:00": "October 1, 08:00",
  "10 月 02 日 08:00": "October 2, 08:00",
  "确认赞成出售": "Confirm vote to approve the sale",
  "确认反对出售": "Confirm vote against the sale",
  "已投赞成票": "Voted to approve",
  "已投反对票": "Voted against",
  "预估整机日产出 ": "Est. miner output ",
  "Task {task}，算力 H = {hash}": "Task {task}, Hashrate H = {hash}",
  "最近日产出：": "Latest daily output: ",
  "共同持有矿机": "Co-owned miners",
  "共 ": "Total: ",
  " 个份额": " shares",
  "查看资金与明细": "View funds and details",
  "矿机转让": "Miner transfers",
  "挂牌中的份额卖方仍保留收益权，成交时先结清卖方收益，成交款扣除 1% 平台费后待领取。": "Sellers retain reward rights while shares are listed. Accrued rewards are settled at sale; proceeds are claimable after a 1% platform fee.",
  "约 99%": "Approx. 99%",
  "日期· 时间(UTC + 8)": "Date · Time (UTC+8)",
  "日期和时间": "Date and time",
  "日期和时间(UTC + 8),类型,矿机,金额,币种,演示记录": "Date and time (UTC+8),Type,Miner,Amount,Asset,Demo record",
  "每份拥有该矿机约 1% 的分配权益": "Each share carries approximately 1% of the miner’s distribution rights",
  "矿机实际产出中，99% 分配给出资人，1% 用于平台运营费用。": "99% of actual mining output is distributed to contributors; 1% covers platform operations.",
  "04 · 独自决定份额": "04 · Control your shares",
  "成员可以独自定价出售自己矿机的份额，份额转让成交扣除 1% 平台费，持有份额的该成员取得余额。": "Members can set their own share sale price. A completed share transfer deducts a 1% platform fee; the selling member receives the balance.",
  "05 · 共同决定退出": "05 · Decide an exit together",
  "出售需要地址数和份额双过半。本站整机成交扣除 1% 平台费，所有成员按持有份额分得余额。": "A sale requires majorities of both wallets and shares. Whole-miner sales deduct a 1% platform fee; all members receive the balance according to their shares.",
  "这台矿机暂无收益记录": "No reward records for this miner yet",
  "资产认购价格": "Total subscription cost",
  "当前份额持有人数": "Current share holders",
  "{count} 人": "{count} holders",
  "矿机日产": "Daily miner output",
  "每份收益": "Daily reward per share",
  "我": "You",
  "转让份额": "Transfer shares",
  "这台矿机暂不支持份额转让": "Shares in this miner cannot be transferred at this stage",
  "合资购买矿机总金额": "Total pooled miner purchases",
  "份额交易金额": "Share trading volume",
  "累计分配": "Total distributed",
  "认购价已含外部商城 1% 买方费用": "Subscription cost includes the external marketplace’s 1% buyer fee",
  "商城矿机标价": "Marketplace miner price",
  "商城买方费用 · 1%": "Marketplace buyer fee · 1%",
  "募集完成，等待购机": "Fully funded, awaiting purchase",
  "暂无可转让的矿机份额": "No miner shares available for transfer",
  "演示挂单已撤销，份额已解锁": "Demo listing cancelled. Shares unlocked.",
"到期日期和时间(UTC + 8)":"Expiry date and time (UTC+8)",
"请先撤销当前演示挂单，再创建新挂单":"Cancel your current demo listing before creating another",
"这台矿机暂无进行中的提案":"No active proposal for this miner",
  "收益已入账，随时可领取": "Booked rewards are ready to claim",
  "已入账权益永久保留": "Booked entitlements never expire",
  "累计入账收益": "Total booked rewards",
  "我的每日入账 · BEM": "My daily booked rewards · BEM",
  "最近每日入账：": "Recently booked per day: ",
  "已入账收益 · 演示": "Booked rewards · Demo",
  "查看可领取收益": "View claimable rewards",
  "募集目标（含预留）": "Funding target including reserve",
  "低于实际购机成本需至少 60 份赞成；其余需超过 50 份，均须快照地址数过半。": "Below purchase cost: at least 60 shares must approve. Otherwise: over 50 shares. Both require a majority of snapshot wallets.",
  "池子购机满 7 天后可提案；全池及每位提案人均须间隔 7 天，投票与执行共用 24 小时。": "Proposals open 7 days after the pool purchases its miner. Both the pool and proposer have a 7-day interval; voting and execution share a 24-hour window.",
  "目标按参考价额外预留 10%；购机余款按份额退还": "Funding includes a 10% reserve above the reference price. Unspent purchase funds are refundable by share.",
  "矿机参考价格": "Reference miner price",
  "筹资预留 · 10%": "Funding reserve · 10%",
  "出售门槛已通过 · 挂牌剩余 5 天 12 小时": "Sale approval thresholds met · 5 days 12 hours left",
  "投票期间及整机挂牌期间暂停份额转让与成交，已有份额挂单仍可撤销解锁。": "Share transfers and fills pause during voting and whole-miner listings. Existing share orders can still be cancelled to unlock shares.",
  "先将收益归集到池子，再由本人领取自己的已入账权益。": "Collect rewards into the pool first, then personally claim your booked entitlement.",
  "已入账收益永久保留，无领取间隔": "Booked rewards never expire and have no claim cooldown",
  "已入账收益": "Booked rewards",
  "按北京时间展示；权益永久保留，转让份额不带走旧收益": "Times are UTC+8. Entitlements remain permanently; transferring shares does not transfer past rewards.",
  "权益有效期": "Entitlement validity",
  "领取方式": "How to claim",
  "任何人都可发起归集，BEM 留在池子；本人领取只支付给本人。有新入账即可再次领取，无 24 小时限制。": "Anyone can collect rewards into the pool. Personal claims pay only the caller. New booked income can be claimed immediately, with no 24-hour cooldown.",
  "份额转让前的已归属收益永久归原持有人，即使份额全部转出仍可本人领取。": "Previously accrued rewards remain permanently with the original holder, who can claim them even after transferring all shares.",
  "出售门槛已达成，请在截止前执行挂牌。": "Sale thresholds met. Execute the listing before the deadline.",
  "地址与份额两道门槛": "Wallet and share thresholds",
  "地址数必须严格过半。低于实际购机成本须至少 60 份赞成，其余须超过 50 份；参考价不替代购机成本。": "A strict wallet majority is required. Below actual purchase cost, at least 60 shares must approve; otherwise, over 50 shares. Reference prices do not replace acquisition cost.",
  "BNB 与已入账 BEM 均可随时由本人领取。": "You can personally claim BNB and booked BEM at any time.",
  "投票后不能修改。达到该提案的地址与份额门槛后，任何人可在截止前执行挂牌。": "Votes cannot be changed. Once the proposal meets its wallet and share thresholds, anyone can execute it before the deadline.",
  "该提案门槛已达成。按批准价格 8.6000 BNB 挂牌，有效期为 7 天；到期后任何人可解除挂牌。": "This proposal meets its thresholds. List at the approved 8.6000 BNB price for 7 days. Anyone can clear the listing after expiry.",
  "池子购机满 7 天后，当前持有人可提案；全池与个人均间隔 7 天。投票与执行窗口为 24 小时，期间份额转让冻结。": "Current holders may propose 7 days after the pool purchases its miner. Both pool-wide and per-wallet intervals are 7 days. Voting and execution share 24 hours, during which share transfers are frozen.",
  "03 · 归集后本人领取": "03 · Collect, then claim personally",
  "任何人可把矿机收益归集到池子；个人自行领取已入账 BEM，无领取间隔，权益永久保留，不销毁。": "Anyone may collect mining rewards into the pool. Individuals claim their own booked BEM without a cooldown. Entitlements never expire and are not burned.",
  "出售须快照地址数过半；低于实际购机成本需至少 60 份赞成，其余需超过 50 份。整机成交扣除 1% 平台费，剩余款按份额领取。": "Sales require a majority of snapshot wallets and, below actual purchase cost, at least 60 approving shares; otherwise, over 50. A 1% fee is deducted and holders claim the remaining proceeds by share.",
  "份额挂牌有效期 7 天，锁定份额仍归卖方并享有收益；成交前严格结清旧收益，扣除 1% 平台费后待本人领取。": "Share listings last 7 days. Locked shares remain the seller’s and retain rewards. Old rewards must settle before a fill; proceeds are personally claimable after a 1% fee.",
  "仅可挂牌未锁定份额，有效期 7 天。投票冻结时不能新增挂单或成交，但可撤单；到期后任何人可解锁。卖方承担 1% 成交费。": "List only unlocked shares for 7 days. Voting freezes new listings and fills, while cancellations remain available. Anyone may unlock expired orders. The seller pays a 1% fee.",
  "产出先归集到池子，个人按份领取；已入账收益永久保留。": "Output is collected into the pool, then personally claimed by share. Booked rewards never expire.",
  "地址数须过半；折价出售需至少 60 份赞成，其余需超过 50 份。": "A wallet majority is required. Sales below acquisition cost need at least 60 approving shares; others need over 50.",
  "查看归集、分配与本人领取记录，了解每一份权益。": "Review collections, allocations and personal claims to understand your rights.",
  "实际购机成本": "Actual acquisition cost",
  "目标募集金额为参考价加 10% 预留，购机余款按份额领取。价格筛选与日产能价统一按当前列示金额计算：募集目标、实际购机成本或整机挂牌价。预览小数仅作展示，不用于构造交易。": "Funding targets include a 10% reserve above the reference price; unspent funds are claimable by share. Filters and price per daily BEM use the displayed funding target, actual acquisition cost or whole-miner asking price. Preview decimals are not used to construct transactions.",
  "挖矿平台费": "Mining platform fee",
  "永久保留": "Never expires",
  "未归集的矿机收益尚未入账；归集不会直接向个人钱包付款。": "Uncollected mining income is not yet booked. Collection does not pay individual wallets.",
  "有效期 7 天": "Valid for 7 days",
  "归集矿机收益": "Collect miner rewards",
  "任何人都可发起归集，矿机产出进入对应池子；扣除 1% 平台费后记入持有人权益，不向发起人支付奖励。": "Anyone can collect mining output into its pool. After a 1% platform fee, it is booked for holders; the caller receives no reward.",
  "本预览仅演示流程，不发送交易；正式操作需对每个池子确认归集交易。": "This preview sends no transactions. Live collection requires confirming a transaction for each pool.",
  "归集流程演示完成；个人仍需自行领取": "Collection demo completed; holders still claim personally",
  "演示归集到池子": "Demo: collect into pool",
  "本人领取已入账收益": "Personally claim booked rewards",
  "每个池子分别由本人签名领取，只支付到本人地址；逐笔确认成功后更新余额。": "Sign a personal claim for each pool. Payment goes only to your address, and balances update after each confirmed transaction.",
  "本池领取演示完成，未发送真实交易": "This pool’s claim demo is complete. No real transaction was sent.",
  "演示本人领取": "Demo personal claim",
  "跨池领取需要逐池签名，不提供代领他人收益的入口。": "Cross-pool claims require a signature for each pool. There is no entry point to claim on someone else’s behalf.",
  "筹资预留不授权加价；购机受参考总价及单位权重上限约束。本次仅演示，不扣款、不发送交易。": "The funding reserve does not authorize a higher purchase price. Both reference-price and unit-weight price limits apply. This is a demo: no funds or transactions are sent.",
  "相对购机成本": "Against acquisition cost",
};
