const en = {
  '报价需人工审核，平台已批准。':'This price needs review; the platform has approved it.',
  '报价需人工审核，等待管理员处理。':'This price needs review; an administrator will process it.',
  '报价符合免审核范围，无需额外审核。':'This price is within the range that requires no additional review.',
  '金额按精确整数发送；请在钱包中确认本次交易。':'Exact integer amounts are sent. Confirm this transaction in your wallet.',
  '表决达到门槛后，挂牌仍需通过当前市场参考价与平台审核核验。':'A passed vote still needs a current market reference and the applicable platform review before listing.',
  'Firsto 市场参考价：':'Firsto market reference: ',
  '暂不可用':'unavailable', '。':'. ',
  '低于购机成本，需至少 60 份赞成；此阶段不使用平台折价审核。':'Below purchase cost: at least 60 yes shares are required. Platform discount review does not apply at this stage.',
  '不低于购机成本，需人数与份额过半；此阶段不使用平台折价审核。':'At or above purchase cost: a majority of members and shares is required. Platform discount review does not apply at this stage.',
  '平台已驳回该提案，禁止挂牌。':'The platform rejected this proposal; listing is blocked.',
  '平台已驳回该提案，禁止折价挂牌。':'The platform rejected this proposal; discounted listing is blocked.',
  '该子矿机尚未满足创世版出售条件。':'This miner has not met the genesis sale conditions.',
  '订单分页来源已变化，请重新读取。':'The order page changed. Reload this miner’s orders from the first page.',
  '平台已驳回这项子矿机出售提案。':'The platform rejected this miner sale proposal.',
  '低于 Firsto 市场参考价，尚待平台审核通过。':'Below the Firsto market reference; platform approval is pending.',
  '市场参考价不可用，挂牌暂不可执行。':'The market reference is unavailable; listing is blocked.',
  '平台审核状态不可用，挂牌暂不可执行。':'The platform review status is unavailable; listing is blocked.',
  '低于市场参考价，平台已批准折价挂牌。':'Below the market reference; the platform approved this discounted listing.',
  '低于市场参考价，等待平台审核。':'Below the market reference; platform review is pending.',
  '不低于市场参考价，无需额外审核。':'At or above the market reference; no additional review is required.',
  '本轮子矿机出售候选':'Miner sale candidates in this round',
  '持有至少 10 份的成员可在同一轮提出候选，大家逐项投票；每轮最多 16 项。提案期间项目份额冻结，其他矿机继续归集收益。':'Members with at least 10 shares may propose candidates in the same round. Everyone votes on each. Each round allows up to 16 candidates. Portfolio share transfers pause during the vote while other miners keep earning.',
  '创世版持有至少 1 份即可发起提案；每轮只有一项，正在投票时不能再发起。':'In the genesis version, a holder with at least one share may propose. Each round accepts one proposal, and no new proposal can start while voting is open.',
  '创世版每轮只允许一项出售提案。下一轮最早':'The genesis version allows one sale proposal per round. The next round starts no earlier than',
  '项目当前不在运行状态，不能发起出售。':'The portfolio is not active and cannot propose a sale.',
  '持有至少 1 份项目份额才能发起出售。':'At least one portfolio share is required to propose a sale.',
  '本轮已有进行中的出售提案，请等待结算或投票结束。':'A sale proposal is already open this round. Wait for settlement or voting to end.',
  '下一轮出售提案尚未开放。':'The next sale proposal round is not yet open.',
  '发起出售候选需持有至少 10 份；你仍可参与投票。':'At least 10 shares are required to propose a sale candidate. You can still vote.',
  '我确认以 0 BNB 免费转出这些份额。':'I confirm that these shares may transfer for free at 0 BNB.',
  ' 这是免费转出挂单，成交后不会收到 BNB。':' This is a free transfer listing. You will receive no BNB on fill.',
  '人':'members','发起逐台出售候选':'Propose a miner sale candidate',
  '正在投票的轮次允许其他持份人提出候选；下一轮最早':'Other holders may propose candidates during the current vote. The next round starts no earlier than',
  '预览出售候选':'Preview sale candidate',
  '出售我的项目份额':'Sell my portfolio shares','已自动选择当前持仓项目，可售份额：':'Your holding is selected automatically. Available shares:',
  '/ 100 份':'/ 100 shares','/ 100 份。':'/ 100 shares.','BNB / 100 份；单机上限':'BNB / 100 shares; per-miner cap',
  'BNB · 合约价格上限':'BNB · Contract price cap','BNB · 已购机':'BNB · Spent on miners','BNB · 我的可转份额':'BNB · My transferable shares',
  'BNB · 赞成':'BNB · Yes votes','BNB。募集截至':'BNB. Funding deadline','BNB。款项来自项目预算，本钱包只付 Gas。':'BNB. Paid from the portfolio budget; this wallet pays Gas only.',
  'BNB；买卖双方各收成交价的 1%。':'BNB; buyer and seller each pay 1% of the base price.','BNB；买方另付':'BNB; additional buyer fee','BNB；卖方扣除':'BNB; seller fee withheld',
  'BNB；全部成交基价':'BNB; total asking price',
  'BNB；挂牌时本钱包仅支付 Gas，买卖双方在成交时各承担基价的 1%。':'BNB; this wallet pays only Gas when listing. The buyer and seller each pay 1% of the base price when the shares sell.',
  'BNB；参考价':'BNB; reference price','BNB；每单位核验算力上限':'BNB; cap per verified weight unit','BNB；观察时间':'BNB; observed at',
  '· 区块 #':'· Block #','· 本次含来源费报价':'· Quote including source fee',
  '。提案发起后本轮项目份额暂时冻结。':'. Starting the proposal temporarily freezes portfolio share trading for this round.',
  '。未领取 BEM 随转出份额按比例移动；历史 BNB 余款和卖款留给原持有人。':'. Unclaimed BEM moves with transferred shares proportionally. Historical BNB refunds and sale proceeds stay with the original holder.',
  '买入份数':'Shares to buy','买方另付成交价的 1%，卖方从成交价扣除 1%。未领取 BEM 随份额按比例移动，历史 BNB 债权不随份额转移。治理期间暂停新增挂单和成交，原挂单仍可撤销。':'The buyer pays an additional 1%; 1% is withheld from the seller. Unclaimed BEM follows transferred shares; historical BNB credits do not. New listings and fills pause during governance, while cancellation remains available.',
  '买方另付成交价的 1%，卖方从成交价扣除 1%。成交时尚未领取的 BEM 随份额按比例移动；卖方有份额挂单锁定时不能先领取 BEM。历史 BNB 债权不随份额转移。治理期间暂停新增挂单和成交，原挂单仍可撤销。':'The buyer pays an additional 1%; 1% is withheld from the seller. BEM unclaimed at settlement moves proportionally with the shares; sellers cannot claim BEM while shares are locked in a listing. Historical BNB credits stay with the seller. New listings and fills pause during governance; existing listings may be cancelled.',
  '人。提案期间项目份额冻结，其他矿机继续归集收益。':'holders. Portfolio share trading freezes while the proposal is live; other miners can still collect rewards.',
  '份':'shares','份数':'Share quantity','份额订单 #':'Share order #','份，':'shares,','份，无对价。':'shares, without payment.','份，每份':'shares, at',
  '先在上方运营工作台选矿机创建一个尚无人认购的单机池，再在这里选择对应子矿池。系统核对官网挂牌并优先官网采购；官网无符合上限的原目标时才校验 Firsto 签名单。成员不用再向子池出资。':'Select a miner and create an unsubscribed child pool above, then choose its address here. The system prioritizes the official listing and checks a Firsto signed ask only when the original official target is unavailable within the cap. Members do not fund the child separately.',
  '创建多矿机预算项目':'Create a multi-miner portfolio','刷新项目':'Refresh portfolios','剩余份额 / 每份价':'Remaining shares / unit price',
  '加载更多子矿机':'Load more miners','加载更多挂单':'Load more orders','加载更多记录':'Load more records','加载更多预算项目':'Load more portfolios',
  '募集期（小时）':'Funding period (hours)','募集结束后购机期（小时）':'Acquisition period after funding (hours)',
  '募集预算':'Funding budget','募集预算（BNB）':'Funding budget (BNB)','区块':'Block','单机价格上限（BNB）':'Per-miner price cap (BNB)',
  '卖方':'Seller','反对':'Oppose','发起逐台出售提案':'Propose a miner sale','发送到钱包确认':'Send to wallet for confirmation',
  '可领 BNB':'Claimable BNB','台购入':'purchased','台运行 /':'active /','向':'To','多矿机预算项目':'Multi-miner portfolios',
  '子矿机出售提案 #':'Miner sale proposal #','子矿池':'Child pool','导出已加载记录':'Export loaded records','已入账 BEM':'Accounted BEM','当前链上可领取':'Currently claimable on-chain',
  '已认购':'Subscribed','结束募集并开启退款':'End funding and enable refunds','归集该台 BEM':'Collect this miner’s BEM','归集该台卖款':'Collect this miner’s sale proceeds',
  '当前没有':'No','待采购子矿池地址':'Child pool to purchase','成交基价':'Base trade price','我的份额':'My shares','执行该台挂牌':'Execute miner listing',
  '拟售价':'Proposed sale price','拟售价格（BNB）':'Proposed sale price (BNB)','挂卖':'List','挂牌份数':'Shares to list',
  '接收人取得对应未领取 BEM 及未来权益；已结算的历史 BNB 余款和卖款保留在你的地址。此操作是赠予转移，不会收取对价。':'The recipient receives proportional unclaimed BEM and future rights. Settled historical BNB refunds and sale proceeds stay at your address. This is a gift transfer with no payment.',
  '接收钱包':'Recipient wallet','撤回我的认购':'Withdraw my subscription','撤销挂单':'Cancel order','操作':'Actions',
  '整个项目共 100 份，共同持有项目内多台矿机。每台矿机的出售单独表决，余款与收益归项目份额持有人。':'The entire portfolio has 100 shares across multiple miners. Each miner sale is voted on separately; remaining funds and rewards belong to portfolio holders.',
  '暂无本项目挂单。':'No orders for this portfolio.','暂无该项目已确认记录。':'No confirmed records for this portfolio.','本次支付':'Payment','来源':'Source',
  '查看交易 ↗':'View transaction ↗','查看矿机与项目操作':'View miners and portfolio actions','正在核对预算项目…':'Verifying portfolios…','正在读取项目记录…':'Reading portfolio records…',
  '每份':'Per share','每份价格（BNB）':'Price per share (BNB)','每单位核验算力上限（BNB）':'Cap per verified weight unit (BNB)',
  'Firsto 市场参考日产能价':'Firsto market reference daily capacity price',
  '日产能价上限（BNB / (BEM / 天)）':'Daily capacity price cap (BNB / (BEM / day))',
  '输入日产能价上限':'Entered daily capacity price cap',
  '输入的日产能价上限':'Entered daily capacity price cap',
  '换算后的链上每 H 上限':'Converted on-chain cap per H',
  '刷新市场产能':'Refresh market output',
  '天':'day',
  '预算项目固定 100 份；总预算、单机绝对上限及换算后的每 H 限价写入合约，采购不能突破这些链上限额。':'Each portfolio has 100 shares. The total budget, per-miner cap and converted price cap per H are enforced on-chain.',
  '输入日产能价上限后，系统按当前 Firsto 样本的最低日产出 / H 比率向下折算为链上每 H 上限；合约不会随未来产能变化自动更新。':'The entered daily capacity cap is rounded down to an on-chain BNB/H cap using the lowest daily output per H in the current Firsto sample. The contract does not adjust when future output changes.',
  'BNB；链上每 H 上限':'BNB; on-chain cap per H', 'BNB / H。募集截至':'BNB/H. Funding closes',
  '日产能价用于比较报价；当前已部署合约按每 H 价格限制购机，不能把日产能价直接填入链上上限。':'Daily capacity price helps compare quotes. The deployed contract enforces a BNB/H cap; do not enter the daily capacity price as that cap.',
  '链上每 H 价格上限（BNB / H）':'On-chain price cap (BNB / H)',
  '状态':'Status','用本项目预算采购矿机':'Purchase miners using this portfolio budget','目标':'Target','结束购机并结算余款':'End acquisition and settle unused funds',
  '结算我的募集退款':'Settle my funding refund','自动核价并预览采购':'Check price and preview purchase','观察到的参考价（BNB）':'Observed reference price (BNB)',
  '募集已到期。此操作结束整个项目的募集，并开启所有成员的退款申请；不会自动向任何人转账。':'Funding has ended. This action ends funding for the entire portfolio and enables refund requests for all members; it does not automatically transfer funds to anyone.',
  '仅撤回你的全部认购，其他成员不受影响。退款记入你的待领 BNB，结算后由你领取。':'Only your entire subscription is withdrawn; other members are unaffected. Your refund is credited to your claimable BNB for you to withdraw after settlement.',
  '仅结算你的募集退款，其他成员不受影响。退款记入你的待领 BNB，结算后由你领取。':'Only your funding refund is settled; other members are unaffected. Your refund is credited to your claimable BNB for you to withdraw after settlement.',
  '份额转让':'Share trading','买卖本项目份额，或领取已成交的卖款。':'Buy or sell shares in this portfolio, or withdraw proceeds from completed sales.',
  '交易规则':'Trading rules','刷新挂单':'Refresh orders','领取转让卖款':'Withdraw share sale proceeds','重新读取转让卖款':'Reload share sale proceeds',
  '撤单处理中…':'Cancelling…',
  '解锁到期挂单':'Unlock expired order','解除过期子机提案':'Clear expired miner proposal','订单':'Order','认购':'Subscribe to','认购份数':'Subscription shares','记录':'Record',
  '该项目尚未购入矿机。':'This portfolio has not purchased any miners.','读取本项目挂单':'Load portfolio orders','读取项目收益与记录':'Load portfolio rewards and records',
  '赞成':'Support','转移':'Transfer','转移项目份额':'Transfer portfolio shares','返回':'Back',
  '这里仅统计进入本预算项目的 BEM，避免与子矿池重复计入；个人未领取权益以项目当前读数为准。':'Only BEM received by this parent portfolio is counted here, without adding child-pool harvests again. Current on-chain balances determine personal unclaimed rights.',
  '卖款结算后仍可归集已售子矿池的 BEM；未归集的 BEM 随项目份额转移。':'BEM from a sold miner can still be collected after its sale proceeds settle. Uncollected BEM follows portfolio shares when they move.',
  '连接钱包查看项目权益':'Connect wallet to view portfolio rights','采购来源 / 成本':'Purchase source / cost',
  '金额按精确链上整数发送；发送前重新核对内容，并先保存交易意图。':'Amounts use exact on-chain integers. Details are rechecked and the transaction intent is saved before requesting a wallet confirmation.',
  '链上凭证':'On-chain proof','项目内矿机':'Portfolio miners','项目收益与公开记录':'Portfolio rewards and public records','项目详情':'Portfolio details',
  '预算':'Budget','预算项目':'Portfolio','预算项目。':'portfolios.','预算项目份额市场':'Portfolio share market','预算项目合约尚未完成部署验收。':'Portfolio contracts have not completed deployment verification.',
  '预算项目固定 100 份；总预算、单机绝对上限和单位算力价格上限写入合约，采购不能突破上限。':'Each portfolio has 100 shares. The contract enforces the total budget, per-miner price cap and price cap per verified weight unit.',
  '先创建共享 100 份的预算项目；募满后在项目中设置本批最多采购台数（1–20 台），从当前合格挂单逐台核验并买入。矿机可能在募集期间售出，因此创建时不锁定具体编号；同一项目可用剩余预算继续采购下一批。':'Create a portfolio with 100 shared units first. After funding, choose up to 20 miners for each batch and verify and purchase them one by one from current eligible listings. Miner listings can sell out during funding, so creation does not lock token IDs; another batch can use any remaining budget.',
  '预算项目每轮只审议一台矿机，下一轮最早':'Each portfolio round considers one miner. The next round can start at',
  '预览 Firsto 购买':'Preview Firsto purchase','预览买入':'Preview buying','预览份额转移':'Preview share transfer','预览出售提案':'Preview sale proposal',
  '预览创建预算项目':'Preview portfolio creation','预览挂卖份额':'Preview share listing','预览认购':'Preview subscription','预览领取预算市场 BNB':'Preview market BNB withdrawal',
  '领取':'Claim','，购机截至':'; acquisition deadline','；挂牌价':'; listing price','；提案 #':'; proposal #',
  '有份额挂单仍在锁定。未领 BEM 继续显示在上方；请先撤单，或等待挂单成交、到期解锁后再领取。':'Shares are locked in an open listing. Your unclaimed BEM remains visible above. Cancel the listing, or wait for it to fill or expire and unlock before claiming.',
  '即使只挂单 1 份，该钱包在此预算项目的全部 BEM 领取也会暂停，包含未挂单份额。请先撤单，或等待挂单成交、到期解锁后再领取。':'Listing even one share pauses all BEM claims for this wallet in this portfolio, including unlisted shares. Cancel the listing, or wait until it fills, expires or unlocks before claiming.',
  '挂单即使只有 1 份，也会暂停此钱包在本预算项目的全部 BEM 领取，直到挂单成交、撤销或到期解锁。':'Listing even one share pauses all BEM claims for this wallet in this portfolio until the listing fills, is cancelled, or expires and unlocks.',
  '合约价格上限仅约束矿机价格，官网服务费另外在购机期结算时从余款扣除；按本次报价计算，项目含费支出最多':'The contract cap applies only to the miner price. The official fee is deducted from unused funds at acquisition settlement; for this quote, project spending including the fee is at most',
  '份额挂单仍在锁定；请先撤单或等待成交、到期解锁后再领取 BEM。':'Shares are locked in an open listing. Cancel it, or wait for it to fill or expire and unlock before claiming BEM.',
  '；未通过提案到期后自动恢复份额转让。':'. Share transfers resume automatically when an unexecuted proposal expires.',
  '认购预算份额':'Subscribe to portfolio shares','领取项目 BEM':'Claim portfolio BEM','领取项目 BNB':'Withdraw portfolio BNB','提出子矿机出售':'Propose miner sale',
  '提交子矿机表决':'Vote on miner sale','执行子矿机挂牌':'Execute miner listing','创建预算项目':'Create portfolio','自动核价采购':'Check price and purchase',
  '挂卖项目份额':'List portfolio shares','买入项目份额':'Buy portfolio shares','撤回份额挂单':'Cancel share listing','解锁到期份额挂单':'Unlock expired share listing','领取预算市场 BNB':'Withdraw portfolio market BNB',
  '募集中':'Funding','购机期':'Acquiring miners','运行中':'Active','出售中':'Listed','已结束':'Closed','可退款':'Refunding',
  '已归集卖款':'Sale proceeds collected','官网':'Official market','现在':'now','与你相关的':'related','本次投赞成票。':'Vote: support.','本次投反对票。':'Vote: oppose.',
  '确认预算项目操作':'Confirm portfolio action','项目区块已变化，请重新展开项目。':'The project block changed. Reopen its details.',
  '确认内容已变化，请重新预览。':'The confirmation changed. Preview again.','请输入整数小时。':'Enter a whole number of hours.',
  '预算历史记录来源不一致。':'Portfolio history sources do not match.','预算项目读取未完成。':'Portfolio reads did not finish.',
};
export const PORTFOLIO_ENGLISH=Object.freeze(en);
export const portfolioText=(locale,text)=>locale==='en'?(en[text]??(/\p{Script=Han}/u.test(text)?`${text} (Translation unavailable.)`:text)):text;
