const en = {
  '出售我的项目份额':'Sell my portfolio shares','已自动选择当前持仓项目，可售份额：':'Your holding is selected automatically. Available shares:',
  '/ 100 份':'/ 100 shares','/ 100 份。':'/ 100 shares.','BNB / 100 份；单机上限':'BNB / 100 shares; per-miner cap',
  'BNB · 合约价格上限':'BNB · Contract price cap','BNB · 已购机':'BNB · Spent on miners','BNB · 我的可转份额':'BNB · My transferable shares',
  'BNB · 赞成':'BNB · Yes votes','BNB。募集截至':'BNB. Funding deadline','BNB。款项来自项目预算，本钱包只付 Gas。':'BNB. Paid from the portfolio budget; this wallet pays Gas only.',
  'BNB；买卖双方各收成交价的 1%。':'BNB; buyer and seller each pay 1% of the base price.','BNB；买方另付':'BNB; additional buyer fee','BNB；卖方扣除':'BNB; seller fee withheld',
  'BNB；全部成交基价':'BNB; total asking price',
  'BNB；挂牌时本钱包仅支付 Gas，买卖双方在成交时各承担基价的 1%。':'BNB; this wallet pays only Gas when listing. The buyer and seller each pay 1% of the base price when the shares sell.',
  'BNB；参考价':'BNB; reference price','BNB；每单位核验算力上限':'BNB; cap per verified weight unit','BNB；观察时间':'BNB; observed at',
  '· 区块 #':'· Block #','· 本次含来源费报价':'· Quote including source fee',
  '。提案发起后本轮项目份额暂时冻结。':'. Starting the proposal temporarily freezes portfolio share trading for this round.',
  '。未领取 BEM 随转出份额按比例移动；历史 BNB 余款和卖款留给原持有人。':'. Unclaimed BEM moves with transferred shares proportionally. Historical BNB refunds and sale proceeds stay with the original holder.',
  '买入份数':'Shares to buy','买方另付成交价的 1%，卖方从成交价扣除 1%。未领取 BEM 随份额按比例移动，历史 BNB 债权不随份额转移。治理期间暂停新增挂单和成交，原挂单仍可撤销。':'The buyer pays an additional 1%; 1% is withheld from the seller. Unclaimed BEM follows transferred shares; historical BNB credits do not. New listings and fills pause during governance, while cancellation remains available.',
  '人。提案期间项目份额冻结，其他矿机继续归集收益。':'holders. Portfolio share trading freezes while the proposal is live; other miners can still collect rewards.',
  '份':'shares','份数':'Share quantity','份额订单 #':'Share order #','份，':'shares,','份，无对价。':'shares, without payment.','份，每份':'shares, at',
  '先在上方运营工作台选矿机创建一个尚无人认购的单机池，再在这里选择对应子矿池。系统核对官网挂牌并优先官网采购；官网无符合上限的原目标时才校验 Firsto 签名单。成员不用再向子池出资。':'Select a miner and create an unsubscribed child pool above, then choose its address here. The system prioritizes the official listing and checks a Firsto signed ask only when the original official target is unavailable within the cap. Members do not fund the child separately.',
  '创建多矿机预算项目':'Create a multi-miner portfolio','刷新项目':'Refresh portfolios','剩余份额 / 每份价':'Remaining shares / unit price',
  '加载更多子矿机':'Load more miners','加载更多挂单':'Load more orders','加载更多记录':'Load more records','加载更多预算项目':'Load more portfolios',
  '募集期（小时）':'Funding period (hours)','募集结束后购机期（小时）':'Acquisition period after funding (hours)',
  '募集预算':'Funding budget','募集预算（BNB）':'Funding budget (BNB)','区块':'Block','单机价格上限（BNB）':'Per-miner price cap (BNB)',
  '卖方':'Seller','反对':'Oppose','发起逐台出售提案':'Propose a miner sale','发送到钱包确认':'Send to wallet for confirmation',
  '可领 BNB':'Claimable BNB','台购入':'purchased','台运行 /':'active /','向':'To','多矿机预算项目':'Multi-miner portfolios',
  '子矿机出售提案 #':'Miner sale proposal #','子矿池':'Child pool','导出已加载记录':'Export loaded records','已入账 BEM':'Accounted BEM','当前链上可领取':'Currently claimable on-chain',
  '已认购':'Subscribed','开启募集失败退款':'Enable failed-funding refunds','归集该台 BEM':'Collect this miner’s BEM','归集该台卖款':'Collect this miner’s sale proceeds',
  '当前没有':'No','待采购子矿池地址':'Child pool to purchase','成交基价':'Base trade price','我的份额':'My shares','执行该台挂牌':'Execute miner listing',
  '拟售价':'Proposed sale price','拟售价格（BNB）':'Proposed sale price (BNB)','挂卖':'List','挂牌份数':'Shares to list',
  '接收人取得对应未领取 BEM 及未来权益；已结算的历史 BNB 余款和卖款保留在你的地址。此操作是赠予转移，不会收取对价。':'The recipient receives proportional unclaimed BEM and future rights. Settled historical BNB refunds and sale proceeds stay at your address. This is a gift transfer with no payment.',
  '接收钱包':'Recipient wallet','撤回全部认购':'Withdraw all subscriptions','撤销挂单':'Cancel order','操作':'Actions',
  '整个项目共 100 份，共同持有项目内多台矿机。每台矿机的出售单独表决，余款与收益归项目份额持有人。':'The entire portfolio has 100 shares across multiple miners. Each miner sale is voted on separately; remaining funds and rewards belong to portfolio holders.',
  '暂无本项目挂单。':'No orders for this portfolio.','暂无该项目已确认记录。':'No confirmed records for this portfolio.','本次支付':'Payment','来源':'Source',
  '查看交易 ↗':'View transaction ↗','查看矿机与项目操作':'View miners and portfolio actions','正在核对预算项目…':'Verifying portfolios…','正在读取项目记录…':'Reading portfolio records…',
  '每份':'Per share','每份价格（BNB）':'Price per share (BNB)','每单位核验算力上限（BNB）':'Cap per verified weight unit (BNB)',
  'Firsto 市场参考日产能价':'Firsto market reference daily capacity price',
  '日产能价上限（BNB / (BEM / 天)）':'Daily capacity price cap (BNB / (BEM / day))',
  '输入日产能价上限':'Entered daily capacity price cap',
  '输入的日产能价上限':'Entered daily capacity price cap',
  '换算后的链上每 H 上限':'Converted on-chain cap per H',
  '刷新市场产能':'Refresh market output',
  '天':'day',
  '预算项目固定 100 份；总预算、单机绝对上限及换算后的每 H 限价写入合约，采购不能突破这些链上限额。':'Each portfolio has 100 shares. The total budget, per-miner cap and converted price cap per H are enforced on-chain.',
  '输入日产能价上限后，系统按当前 Firsto 样本的最低日产出 / H 比率向下折算为链上每 H 上限；合约不会随未来产能变化自动更新。':'The entered daily capacity cap is rounded down to an on-chain BNB/H cap using the lowest daily output per H in the current Firsto sample. The contract does not adjust when future output changes.',
  'BNB；链上每 H 上限':'BNB; on-chain cap per H', 'BNB / H。募集截至':'BNB/H. Funding closes',
  '日产能价用于比较报价；当前已部署合约按每 H 价格限制购机，不能把日产能价直接填入链上上限。':'Daily capacity price helps compare quotes. The deployed contract enforces a BNB/H cap; do not enter the daily capacity price as that cap.',
  '链上每 H 价格上限（BNB / H）':'On-chain price cap (BNB / H)',
  '状态':'Status','用本项目预算采购矿机':'Purchase miners using this portfolio budget','目标':'Target','结束购机并结算余款':'End acquisition and settle unused funds',
  '结算募集退款':'Settle funding refund','自动核价并预览采购':'Check price and preview purchase','观察到的参考价（BNB）':'Observed reference price (BNB)',
  '解锁到期挂单':'Unlock expired order','解除过期子机提案':'Clear expired miner proposal','订单':'Order','认购':'Subscribe to','认购份数':'Subscription shares','记录':'Record',
  '该项目尚未购入矿机。':'This portfolio has not purchased any miners.','读取本项目挂单':'Load portfolio orders','读取项目收益与记录':'Load portfolio rewards and records',
  '赞成':'Support','转移':'Transfer','转移项目份额':'Transfer portfolio shares','返回':'Back',
  '这里仅统计进入本预算项目的 BEM，避免与子矿池重复计入；个人未领取权益以项目当前读数为准。':'Only BEM received by this parent portfolio is counted here, without adding child-pool harvests again. Current on-chain balances determine personal unclaimed rights.',
  '连接钱包查看项目权益':'Connect wallet to view portfolio rights','采购来源 / 成本':'Purchase source / cost',
  '金额按精确链上整数发送；发送前重新核对内容，并先保存交易意图。':'Amounts use exact on-chain integers. Details are rechecked and the transaction intent is saved before requesting a wallet confirmation.',
  '链上凭证':'On-chain proof','项目内矿机':'Portfolio miners','项目收益与公开记录':'Portfolio rewards and public records','项目详情':'Portfolio details',
  '预算':'Budget','预算项目':'Portfolio','预算项目。':'portfolios.','预算项目份额市场':'Portfolio share market','预算项目合约尚未完成部署验收。':'Portfolio contracts have not completed deployment verification.',
  '预算项目固定 100 份；总预算、单机绝对上限和单位算力价格上限写入合约，采购不能突破上限。':'Each portfolio has 100 shares. The contract enforces the total budget, per-miner price cap and price cap per verified weight unit.',
  '先创建共享 100 份的预算项目；募满后在项目中设置本批最多采购台数（1–20 台），从当前合格挂单逐台核验并买入。矿机可能在募集期间售出，因此创建时不锁定具体编号；同一项目可用剩余预算继续采购下一批。':'Create a portfolio with 100 shared units first. After funding, choose up to 20 miners for each batch and verify and purchase them one by one from current eligible listings. Miner listings can sell out during funding, so creation does not lock token IDs; another batch can use any remaining budget.',
  '预算项目每轮只审议一台矿机，下一轮最早':'Each portfolio round considers one miner. The next round can start at',
  '预览 Firsto 购买':'Preview Firsto purchase','预览买入':'Preview buying','预览份额转移':'Preview share transfer','预览出售提案':'Preview sale proposal',
  '预览创建预算项目':'Preview portfolio creation','预览挂卖份额':'Preview share listing','预览认购':'Preview subscription','预览领取预算市场 BNB':'Preview market BNB withdrawal',
  '领取':'Claim','，购机截至':'; acquisition deadline','；挂牌价':'; listing price','；提案 #':'; proposal #',
  '；未通过提案到期后自动恢复份额转让。':'. Share transfers resume automatically when an unexecuted proposal expires.',
  '认购预算份额':'Subscribe to portfolio shares','领取项目 BEM':'Claim portfolio BEM','领取项目 BNB':'Withdraw portfolio BNB','提出子矿机出售':'Propose miner sale',
  '提交子矿机表决':'Vote on miner sale','执行子矿机挂牌':'Execute miner listing','创建预算项目':'Create portfolio','自动核价采购':'Check price and purchase',
  '挂卖项目份额':'List portfolio shares','买入项目份额':'Buy portfolio shares','撤回份额挂单':'Cancel share listing','解锁到期份额挂单':'Unlock expired share listing','领取预算市场 BNB':'Withdraw portfolio market BNB',
  '募集中':'Funding','购机期':'Acquiring miners','运行中':'Active','出售中':'Listed','已结束':'Closed','可退款':'Refunding',
  '已归集卖款':'Sale proceeds collected','官网':'Official market','现在':'now','与你相关的':'related','本次投赞成票。':'Vote: support.','本次投反对票。':'Vote: oppose.',
  '确认预算项目操作':'Confirm portfolio action','项目区块已变化，请重新展开项目。':'The project block changed. Reopen its details.',
  '确认内容已变化，请重新预览。':'The confirmation changed. Preview again.','请输入整数小时。':'Enter a whole number of hours.',
  '预算历史记录来源不一致。':'Portfolio history sources do not match.','预算项目读取未完成。':'Portfolio reads did not finish.',
};
export const PORTFOLIO_ENGLISH=Object.freeze(en);
export const portfolioText=(locale,text)=>locale==='en'?(en[text]??(/\p{Script=Han}/u.test(text)?'The operation could not be verified. Refresh the portfolio and try again.':text)):text;
