"""Generate current v8 review snapshots; archived releases stay outside the public site."""
from pathlib import Path
import hashlib,json
root=Path(__file__).resolve().parents[1]
s=(root/'components/Platform.jsx').read_text()
source_hash=hashlib.sha256(s.encode()).hexdigest()
def replace(old,new):
 global s
 assert old in s,old
 s=s.replace(old,new,1)
replace("import PoolCatalog from './PoolCatalog';", "import PoolCatalog from './PoolCatalogMobileReviewV8';")
replace('export default function Platform(){','export default function PlatformMobileReviewV8({scenario={}}){')
replace("const [appearance,setAppearance]=useState('light');","const [appearance,setAppearance]=useState(scenario.appearance||'light');")
s='\n'.join(line for line in s.split('\n') if "const saved=localStorage.getItem('bemine-appearance')" not in line and "const t=new URLSearchParams(window.location.search)" not in line and "function sync(){const [r,id]=" not in line)
replace("function toggleAppearance(){const next=appearance==='dark'?'light':'dark';setAppearance(next);try{localStorage.setItem('bemine-appearance',next)}catch{}}", "function toggleAppearance(){setAppearance(v=>v==='dark'?'light':'dark')}")
for name,old,new in [
('route',"useState('home')","useState(scenario.route||'home')"),('poolId',"useState('16928')","useState(scenario.poolId||'16928')"),
('menu','useState(false)','useState(scenario.menu||false)'),('modal','useState(null)','useState(scenario.modal||null)'),('toast',"useState('')","useState(scenario.toast?t(scenario.toast,scenario.toastParams):'')"),
('connected','useState(false)','useState(scenario.connected||false)'),('poolList','useState(seedPools)','useState(scenario.pools||seedPools)'),
('filter',"useState('项目总览')","useState(scenario.filter||'项目总览')"),('range',"useState('7D')","useState(scenario.range||'7D')"),
('marketTab',"useState('份额交易')","useState(scenario.marketTab||'份额交易')"),('detailTab',"useState('资产详情')","useState(scenario.detailTab||'资产详情')"),
('qty','useState(5)','useState(scenario.qty??5)'),('claimed','useState(false)','useState(scenario.claimed||false)'),
('voted','useState(null)','useState(scenario.voted||null)'),('listed','useState(false)','useState(scenario.listed||false)'),('recordFilter',"useState('全部记录')","useState(scenario.recordFilter||'全部记录')")]:
 # Match the relevant setter rather than other equal defaults.
 import re
 pattern=r'(\['+name+r',\w+\]=)'+re.escape(old)
 s,count=re.subn(pattern,lambda m:m[1]+new,s,count=1)
 assert count==1,name
replace('initialTab={filter}/>', 'initialTab={filter} reviewState={scenario.catalog||{}}/>')
replace("modalRef.current?.querySelector('button,input')?.focus();", "/* Preview frames must not steal focus while loading. */")
(root/'components/PlatformMobileReviewV8.jsx').write_text('// Generated by scripts/build-mobile-review-v8.py. Review-only snapshot.\n'+s)
c=(root/'components/PoolCatalog.jsx').read_text()
c=c.replace("initialTab = '项目总览'", "initialTab = '项目总览', reviewState = {}")
c=c.replace("useState('')", "useState(reviewState.query||'')",1).replace('useState({ ...DEFAULT_FILTERS })','useState({ ...DEFAULT_FILTERS, ...reviewState.filters })',1).replace("useState('funded-desc')","useState(reviewState.sort||'funded-desc')",1).replace('useState(false)','useState(reviewState.filterOpen||false)',1)
(root/'components/PoolCatalogMobileReviewV8.jsx').write_text('// Generated by scripts/build-mobile-review-v8.py. Review-only snapshot.\n'+c)
(root/'lib/mobile-review-v8-baseline.json').write_text(json.dumps({'release':'20260926-rewards-v8','date':'2026-09-26','platformSha256':source_hash},indent=2)+'\n')
print('Review-only component snapshots generated; product components untouched.')
