#!/usr/bin/env python3
"""Canonicalize existing v5 HTML entries without changing assets or runtime."""
from datetime import datetime, timezone
from pathlib import Path
import hashlib
import json
import os
import shutil
import subprocess
import tempfile
import time

HOST = 'bemine.cc.cd'
CONFIG = Path('/etc/nginx/sites-available/bemine-v4-domain')
SNIPPET = Path('/etc/nginx/snippets/bemine-v5-product.conf')
CURRENT = Path('/var/www/bemine-v5/current')
OLD_ROOT = 'location = / { rewrite ^ /bemine-v5/ last; }'
ROOT = 'location = / { root /var/www/bemine-v5/current; try_files /index.html =404; add_header Cache-Control "no-store" always; }'
UNITS = ['pinkuang-index-v5', 'pinkuang-product-v5', 'pinkuang-v5-purchase',
         'pinkuang-v5-mining', 'pinkuang-v5-signer', 'pinkuang-v5-price']
# Exported HTML pages only. Asset, API and RSC paths never enter this allowlist.
PAGE_ROUTES = ('404', '_not-found', 'budget-share', 'design', 'factory-reuse-upgrade',
               'live', 'mobile-review', 'mobile-review/frame', 'mobile-review/view',
               'native-sale-upgrade', 'posters', 'preview', 'review', 'review/frame',
               'sale-upgrade', 'share/anime', 'share/finance', 'share/future',
               'share/ink', 'share/original', 'share/papercraft', 'share/real',
               'share/space', 'share/tech')
PAGE_MARKER = '# Canonical exported HTML pages: generated by canonical-homepage.py.\n'


def run(*args):
    return subprocess.run(args, check=True, capture_output=True).stdout


def sha(data):
    return hashlib.sha256(data).hexdigest()


def processes():
    return {unit: run('systemctl', 'show', unit, '-p', 'ActiveState', '-p',
                      'SubState', '-p', 'InvocationID', '-p', 'NRestarts') for unit in UNITS}


def fetch(host, path):
    result = run('curl', '--silent', '--show-error', '--connect-timeout', '5',
                 '--max-time', '25', '--resolve', f'{host}:443:127.0.0.1',
                 '-w', '\n__META__%{http_code}\t%{redirect_url}', f'https://{host}{path}')
    body, meta = result.rsplit(b'\n__META__', 1)
    status, redirect = meta.decode().split('\t', 1)
    return int(status), redirect, body


def replace_once(text, old, new):
    if old in text:
        assert text.count(old) == 1, 'Duplicate route; no change allowed.'
        return text.replace(old, new, 1)
    assert text.count(new) == 1, 'Unrecognized route; no change allowed.'
    return text


def page_locations():
    blocks = [PAGE_MARKER.rstrip()]
    for route in PAGE_ROUTES:
        for suffix in ['', '/', '.html']:
            path = '/' + route + suffix
            blocks.append('location = ' + path + ' {\n'
                          '    root /var/www/bemine-v5/current;\n'
                          '    try_files /' + route + '.html =404;\n'
                          '    add_header Cache-Control "no-store" always;\n}')
            blocks.append('location = /bemine-v5' + path + ' {\n'
                          '    add_header Cache-Control "no-store" always;\n'
                          '    return 308 ' + path + '$is_args$args;\n}')
    return '\n'.join(blocks) + '\n'


def canonical_snippet(text):
    text = replace_once(text, 'location = /bemine-v5 { return 308 /bemine-v5/; }',
        '# Only HTML entry points redirect. API, data and immutable assets retain their namespace.\n'
        'location = /bemine-v5 {\n    add_header Cache-Control "no-store" always;\n    return 308 /$is_args$args;\n}')
    for path in ['/bemine-v5/', '/bemine-v5/index.html']:
        old = 'location = ' + path + ' {\n    root /var/www/bemine-v5/current;\n    try_files /index.html =404;\n    add_header Cache-Control "no-store" always;\n}'
        new = 'location = ' + path + ' {\n    add_header Cache-Control "no-store" always;\n    return 308 /$is_args$args;\n}'
        text = replace_once(text, old, new)
    pages = page_locations()
    if PAGE_MARKER in text:
        assert text.count(PAGE_MARKER) == 1 and text.endswith(pages), 'Unexpected existing page routes.'
        return text
    return text.rstrip() + '\n\n' + pages


def atomic_write(path, data):
    fd, name = tempfile.mkstemp(prefix='.canonical-', dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        shutil.copystat(path, name)
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)


def verify(root_sha, release_sha, chunk):
    status, redirect, body = fetch(HOST, '/')
    assert status == 200 and not redirect and sha(body) == root_sha, 'Root homepage changed or redirected.'
    checks = {'root': 200}
    for path in ['/bemine-v5', '/bemine-v5/', '/bemine-v5/index.html']:
        status, redirect, _ = fetch(HOST, path + '?canonical=homepage')
        assert status == 308 and redirect == f'https://{HOST}/?canonical=homepage', (path, status, redirect)
        checks[path] = {'status': status, 'location': redirect}
    pages = []
    for route in PAGE_ROUTES:
        expected_sha = sha((CURRENT / (route + '.html')).read_bytes())
        for suffix in ['', '/', '.html']:
            path = '/' + route + suffix
            status, redirect, body = fetch(HOST, path + '?canonical=page')
            assert status == 200 and not redirect and sha(body) == expected_sha, ('Root page mismatch', path, status)
            old_status, location, _ = fetch(HOST, '/bemine-v5' + path + '?canonical=page')
            assert old_status == 308 and location == f'https://{HOST}{path}?canonical=page', (path, old_status, location)
            pages.append({'path': path, 'status': status, 'legacyStatus': old_status,
                          'queryPreserved': True, 'htmlSha256': expected_sha})
    checks['canonicalPages'] = pages
    for path in ['/bemine-v5/fresh-product-release.json', '/bemine-v5/data/frontend-manifest.v5.json',
                 '/bemine-v5/data/bem-price.json', '/bemine-v5/' + chunk,
                 '/bemine-v5/api/chain-index/v1/display/stats']:
        status, redirect, body = fetch(HOST, path)
        assert status == 200 and not redirect, (path, status)
        if path.endswith('fresh-product-release.json'):
            assert sha(body) == release_sha, 'Static release changed.'
        if path.endswith('/display/stats'):
            assert json.loads(body).get('data') is not None, 'Display data unavailable.'
        checks[path] = status
    for host, path, expected in [(HOST, '/bemine-v4/', 503),
                                 ('tapeout.cc.cd', '/bemine-full-test/', 503),
                                 ('tapeout.cc.cd', '/pinkuang-deploy-latest/', 200)]:
        status, _, _ = fetch(host, path)
        assert status == expected, (host, path, status)
        checks[host + path] = status
    return checks


def main():
    assert os.geteuid() == 0, 'Run on the BEMine web host as root.'
    before = {CONFIG: CONFIG.read_bytes(), SNIPPET: SNIPPET.read_bytes()}
    after = {CONFIG: replace_once(before[CONFIG].decode(), OLD_ROOT, ROOT).encode(),
             SNIPPET: canonical_snippet(before[SNIPPET].decode()).encode()}
    status, redirect, body = fetch(HOST, '/')
    assert status == 200 and not redirect, 'Existing root must be healthy before publication.'
    root_sha = sha(body)
    release_bytes = (CURRENT / 'fresh-product-release.json').read_bytes()
    release = json.loads(release_bytes)
    actual_pages = {str(path.relative_to(CURRENT))[:-5] for path in CURRENT.rglob('*.html') if path.is_file()}
    assert actual_pages == {'index', *PAGE_ROUTES}, 'Exported HTML inventory changed; review its route allowlist first.'
    chunk = next(str(p.relative_to(CURRENT)) for p in sorted((CURRENT / '_next/static').rglob('*.js')) if p.is_file())
    process_before = processes()
    assert all(b'ActiveState=active' in value and b'SubState=running' in value for value in process_before.values()), 'Runtime inactive.'
    backup = Path('/root') / ('bemine-canonical-homepage-' + datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ'))
    backup.mkdir(mode=0o700)
    for path, data in before.items():
        (backup / path.name).write_bytes(data)
    changed = any(before[path] != data for path, data in after.items())
    try:
        if changed:
            for path, data in after.items():
                atomic_write(path, data)
            run('nginx', '-t')
            run('systemctl', 'reload', 'nginx')
        # Allow old nginx workers to finish their graceful reload before validation.
        for attempt in range(15):
            try:
                checks = verify(root_sha, sha(release_bytes), chunk)
                break
            except AssertionError:
                if attempt == 14:
                    raise
                time.sleep(1)
        assert processes() == process_before, 'A runtime process changed during route publication.'
        receipt = {'schemaVersion': 1, 'status': 'published' if changed else 'already-active',
                   'publishedAt': datetime.now(timezone.utc).isoformat(), 'publicUrl': f'https://{HOST}/',
                   'frontendSourceHead': release['frontendSourceHead'], 'runtimeSourceHead': release['runtimeSourceHead'],
                   'rootHtmlSha256': root_sha, 'releaseManifestSha256': sha(release_bytes),
                   'serviceProcessesUnchanged': True, 'runtimeRestarted': False, 'httpChecks': checks,
                   'configHashes': {path.name: {'before': sha(before[path]), 'after': sha(data)} for path, data in after.items()},
                   'rollbackDirectory': str(backup)}
        (backup / 'publication.json').write_text(json.dumps(receipt, indent=2) + '\n')
        print(json.dumps(receipt))
    except Exception:
        if changed:
            for path, data in before.items():
                atomic_write(path, data)
            run('nginx', '-t')
            run('systemctl', 'reload', 'nginx')
        raise


if __name__ == '__main__':
    main()
