// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.24;

/// @notice Official task-1 AND vectors, solely for local protocol fork probes.
/// @dev Generated by scripts/m0/generate-start-fixture.mjs. Source: https://tapeout.net/pod/pod-vectors-all.json
/// Full vector-bank SHA-256: 2b087560556859b589abac43ac9aac92a7f7a87a023a51e2e4d967c53efd80eb
/// Algorithm source: https://tapeout.net/pod/assets/main-C1q9aWV9.js
/// Leaves are double keccak256 of ABI(index,input,out); pairs are lexically sorted.
library MiningStartFixtures {
    bytes32 internal constant TASK_ROOT = 0x850c8ad5850c125982a71d3ecf96bd485f1f25a600bec4e02559e9413e16cc63;
    uint32 internal constant TASK_ID = 1;
    uint32 internal constant CYCLES = 1;
    uint32 internal constant VECTOR_COUNT = 256;

    function vectors() internal pure returns (bytes memory inputs, bytes memory outputs) {
        inputs =
            hex"00030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103020300030103";
        outputs =
            hex"00010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001000100010001";
    }

    function tree() internal pure returns (bytes32[] memory nodes) {
        (bytes memory inputs, bytes memory outputs) = vectors();
        nodes = new bytes32[](512);
        for (uint32 i; i < VECTOR_COUNT; ++i) {
            nodes[256 + i] = keccak256(
                bytes.concat(keccak256(abi.encode(i, abi.encodePacked(inputs[i]), abi.encodePacked(outputs[i]))))
            );
        }
        for (uint256 i = 255; i > 0; --i) {
            bytes32 left = nodes[2 * i];
            bytes32 right = nodes[2 * i + 1];
            nodes[i] =
                left < right ? keccak256(abi.encodePacked(left, right)) : keccak256(abi.encodePacked(right, left));
        }
        require(nodes[1] == TASK_ROOT, "official vector root mismatch");
    }

    function samples(bytes32 anchorHash, address circuits, uint256 circuitId, uint32 count)
        internal
        pure
        returns (bytes[] memory inputs, bytes[] memory outputs, bytes32[][] memory proofs)
    {
        bytes32[] memory nodes = tree();
        (bytes memory allInputs, bytes memory allOutputs) = vectors();
        inputs = new bytes[](count);
        outputs = new bytes[](count);
        proofs = new bytes32[][](count);
        for (uint32 i; i < count; ++i) {
            uint256 index = uint256(keccak256(abi.encodePacked(anchorHash, circuits, circuitId, i))) % VECTOR_COUNT;
            inputs[i] = abi.encodePacked(allInputs[index]);
            outputs[i] = abi.encodePacked(allOutputs[index]);
            proofs[i] = new bytes32[](8);
            uint256 at = 256 + index;
            for (uint256 depth; depth < 8; ++depth) {
                proofs[i][depth] = nodes[at ^ 1];
                at >>= 1;
            }
        }
    }
}
